### PR TITLE
Migrate remindme commands to new locale

### PR DESCRIPTION
**Pull request by bit-man**
Migrate remindme commands to new locale

### CODE REVIEW

**Review by SrGaabriel — APPROVED** [review]

**Comment by bit-man** [comment]
@SrGaabriel anything else that I can do to make this PR approved or merged?

**Comment by SrGaabriel** [comment]
@bit-man I will contact @MrPowerGamerBR to review this.

**Comment by bit-man** [comment]
@MrPowerGamerBR anything else I can do  to make this PR approved or merged?

**Comment by bit-man** [comment]
Sorry @SrGaabriel @MrPowerGamerBR  to bother you again but I can't see this PR counting for Hacktoborfest. Could you approve it, please, or let me know how to advance to approval o merge?

**Comment by bit-man** [comment]
Thanks!

**Pull request merged**
