### PR TITLE
WIP: German Translation

### PR DESCRIPTION
**Pull request by moelrobi**
This is a Work-In-Progress PR.

I am currently working on a German Translation for the Bot.

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
Thank you for taking your time to translate her! 😊 

By the way, we do have a online translation GUI, but, if you prefer working with JSON files, then no problem 😉 https://loritta.website/translation/de-de

**Comment by moelrobi** [comment]
Finally I can comment. So first of All I need to apoligize. I was locked out of this Account and thats why I couldn't commit to this PR. Next I want to ask: Is a German Translation still needed? @MrPowerGamerBR

**Comment by MrGaabriel** [comment]
Well, I don't think that too many german servers use Loritta, but a german translatiom would be cool to try to expand Lori to Germany.

**Comment by MrPowerGamerBR** [comment]
@moelrobi yes, it is still needed, however the "translation format" changed a bit.

If you see, all translations are now split in different folders, stored in YAML format, not every string is on the YAML file yet tho.

**Comment by moelrobi** [comment]
Should i then create the YML File like this file: https://github.com/LorittaBot/LorittaLocales/blob/master/en-us.yml as example, or keep to the JSON Format for now?

**Pull request closed without merging**
